### ISSUE TITLE
The difference between sciparser and pdf_parser?

### ISSUE THREAD

**Issue by Davidwhw** [davendw49/sciparser#1]
In the article GEOGALACTICA, two PDF parsing tools, `sciparser`  and [`pdf_parser`](https://github.com/Acemap/pdf_parser/tree/main), are introduced. 
I would like to ask what is the difference between these two tools? 
In the introduction of the article, both seem to serve similar functions.

**Comment by davendw49** [comment]
[Acemap/pdf_parser](https://github.com/Acemap/pdf_parser) is the backend of [sciparser](https://github.com/davendw49/sciparser), **pdf_parser** aggregates serveral PDF parsing tools like grobid, pdffigure2, cermine, etc..
