### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by junwenxiong** [davendw49/sciparser#2]
您好，我在运行这份代码时，出现了一个问题，但是看您的gradio demo又是正常运行的，请问下您知道这个问题嘛?
![image](https://github.com/davendw49/sciparser/assets/35716657/4d5ef9cf-882a-41ad-a720-e74fd6ff1ec0)

**Comment by liutaocode** [comment]
Same problem. Have you fixed it?

**Comment by ashmalvayani** [comment]
Same problem, have you found the solution of this?

**Comment by liutaocode** [comment]
> Same problem, have you found the solution of this?

Yes.

You need to run a http service using Docker, for example:

```
docker run --rm --gpus all --init --ulimit core=0 -p 8070:8070 grobid/grobid:0.8.0
```

Then copy `localhost` and port `8070` to the script config.

 The detailed tutorial can be found on [URL](https://grobid.readthedocs.io/en/latest/Run-Grobid/).
