### ISSUE TITLE
Cannot connect to http://10.10.10.10:8074

### ISSUE THREAD

**Issue by ashmalvayani** [davendw49/sciparser#3]
I am constantly getting this error of "Cannot connect to http://10.10.10.10:8074". Shall we change it with our local machine ip or is this an specific server ip of gorbid backend?

**Comment by davendw49** [comment]
The server ip is changeable, meanwhile the `ip` and `port` are corresponding to your grobid server, which you can turn to [Acemap/pdf_parser](https://github.com/Acemap/pdf_parser) to start one.

**Comment by etiennebonnafoux** [comment]
Hello,

I get the same error. So to be clear, shoud we start manually a grobid server ?

**Comment by ashmalvayani** [comment]
@etiennebonnafoux 
To run this, we need to connect to Gorbid Server. For this, install docker and pull the image "Ifoppiano/gorbid:latest-develop" and run it. Make sure it's active.

Then http://10.10.10.10:8074/ shall work fine.
