### ISSUE TITLE
中文文献解析

### ISSUE THREAD

**Issue by MovePhilip** [davendw49/sciparser#5]
你们这个库的中文文献解析能力很弱

**Comment by davendw49** [comment]
Dear sir, this repo is based on Grobid, so we have the same limitations in Chinese documents parsing as Grobid, which you can refer to [grobid issues279](https://github.com/kermitt2/grobid/issues/279), thank you for your kind reminder.

张先生好，本仓库是基于Grobid的解析后端的，因此，我们继承Grobid对于英文的理解，详细汉化组里您可以参考[grobid的issues279](https://github.com/kermitt2/grobid/issues/279)。

谢谢您的鼓励哟，我们也在做中文文献的解析，也已经用在了我们自己的中文模型中，望您之后依然关注😄

**Comment by MovePhilip** [comment]
哈哈哈，你们中文文献解析精度咋样啊，有换成OCR后端吗，我自己也有在做中文文献解析的工作，但是进度很慢

**Comment by davendw49** [comment]
加油！
